locking/local_lock: Remove initialization of non-existent members
There is an error when compiling the kernel with `CONFIG_DEBUG_LOCK_ALLOC`
enabled.

Remove the initialization code of `lock_type`.

```
In file included from ./include/linux/local_lock.h:5,
                 from mm/mmap_lock.c:14:
./include/linux/local_lock_internal.h:21:4: error: ‘struct lockdep_map’ has no member named ‘lock_type’
   .lock_type = LD_LOCK_PERCPU,  \
    ^~~~~~~~~
```

Fixes: 5501aa12d32d ("locking/local_lock: Add missing owner initialization")
Signed-off-by: Gang Li <ligang.bdlg@bytedance.com>