bytedance: export blk_should_fake_timeout() for ublk
This fixes a compiler error when CONFIG_FAIL_IO_TIMEOUT=y:

ERROR: "blk_should_fake_timeout" [drivers/block/ublk_drv.ko] undefined!

Fixes: 9616ece07165 ("ublk_drv: add io_uring based userspace block driver")
Signed-off-by: Xie Yongji <xieyongji@bytedance.com>